### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by takeda** [knoguchi/cm-druid#8]
I did not have a chance to use your parcel yet, but looking at the code it appears that only MySQL is supported.

Could you also add support for PostgreSQL? Both, Druid and Cloudera can work with PostgreSQL.

**Comment by knoguchi** [comment]
The metadata storage is configurable.  MySQL is just a default value.  Actually I'm using PostgreSQL in my cluster.  Please set "postgresql" to the "druid.metadata.storage.type" key.  Don't forget to add "postgresql-metadata-storage" to the druid.extensions.loadList as well.
